hello/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("hossein", views.hossein, name="hossein"),
    path("narges", views.narges, name="narges"),
    path("<str:name>", views.greeting, name="greeting")
]

lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path("tasks/", include("task.urls")),
]

newyear/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
]

task/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

task/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, "hello/index.html")

def hossein(request):
    return HttpResponse("Hello Hossein!")

def narges(request):
    return HttpResponse("Hello Narges!")

def greeting(request, name):
    return render(request, "hello/greeting.html", {
        "name": name.capitalize()
    })

newyear/views.py
from django.shortcuts import render
from datetime import datetime

# Create your views here.


def index(request):
    now = datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.day == 1 and now.month == 1
    })

task/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
# Create your views here.

tasks = ["foo", "bar", "baz"]

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

# def index(request):
#     return render(request, "tasks/index.html", {
#         "tasks": tasks
#     })

# def add(request):
#     if request.method == "POST":
#         form = NewTaskForm(request.POST)
#         if form.is_valid():
#             task = form.cleaned_data["task"]
#             tasks.append(task)
#             return HttpResponseRedirect(reverse("tasks:index"))
#         else:
#             return render(request, "tasks/add.html", {
#                 "form": form
#             })

#     return render(request, "tasks/add.html", {
#         "form": NewTaskForm()
#     })


def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/greeting.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            Greeting
        </title>
    </head>
    <body>
        <h1 style="color: blue;">
            Hello {{ name }}
        </h1>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            Hello
        </title>
    </head>
    <body>
        Hello World!!!.
        <h1 style="color: blue;">
            Hello every one
        </h1>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            Is it Christmas
        </title>
        <link rel="stylesheet" href="{% static "newyear/styles.css" %}">
    </head>
    <body>
        {% if newyear %}
            <h1>Yes</h1>
        {% else %}
            <h1>No</h1>
        {% endif %}
    </body>
</html>

task/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <h1>add tasks:</h1>
    <form action="{% url "tasks:add" %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url "tasks:index" %}">view tasks</a>
{% endblock  %}

task/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
        <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url "tasks:add" %}">add a new task</a>
{% endblock  %}

task/templates/tasks/layout.html
<DOCTYPE html>
    <html lang="en">
        <head>
            <title>Tasks</title>
        </head>
        <body>
            {% block body %}
            {% endblock %}
        </body>
    </html>